version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    branches:
      only:
        - v2
    steps:
      - checkout
      - run: npm install
      - run: npm test